GET http://localhost:3000/tweets



### 
POST http://localhost:3000/tweets
Content-Type: application/json

{
    "Text": "A Imersão começou",
    "User": {
        "Name": "Luiz Carlos"
    }
}

### 
POST http://localhost:3000/tweets
Content-Type: application/json

{
    "CreatedAt": 1644096553000,
    "Text": "A Imersão começou 2",
    "InReplyToStatusId": 1,
    "InReplyToUserId": 1,
    "InReplyToScreenName": "",
    "Place": false,
    "Retweeted": true,
    "FavoriteCount": 1,
    "Retweet": false,
    "RetweetCount": 1,
    "RetweetedByMe": false,
    "CurrentUserRetweetId": "",
    "PossibleSensitive": false,
    "Lang": "PTP",
    "User": {
        "Name": "Luiz Carlos",
        "OriginalProfileImageURL": "",
        "ProfileImageURLHttps": "",
        "BiggerProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1462058322232844295/DTv7M8lC_normal.jpg",
        "MiniProfileImageURLHttps": "",
        "OriginalProfileImageURLHttps": "",
        "DefaultProfileImage": true,
        "URL": "",
        "Protected": false,
        "FollowersCount": 100,
        "ProfileBackgroundColor": "",
        "ProfileTextColor": "",
        "ProfileLinkColor": "",
        "ProfileSidebarFillCollor": "",
        "ProfileSidebarBorderColor": "",
        "ProfileUserBackgroundImage": false,
        "DefaultProfile": true,
        "ShowAllInlineMedia": true,
        "FriendsCount": 2000,
        "CreatedAt": 1644096553000,
        "FavouritesCount": 21321321,
        "Lang": "PT",
        "StatusesCount": 1,
        "GeoEnabled": false,
        "Verified": false,
        "Translator": false,
        "ListedCount": 1,
        "FollowRequestSent": false,
        "ScreenName": "Netflix",
        "Location": "",
        "Description": "",
        "ContributorsEnabled": false,
        "ProfileImageURL": "",
        "BiggerProfileImageURL": "",
        "MiniProfileImageURL": ""
    }
}


### 
POST http://localhost:3000/tweets
Content-Type: application/json

{
    "CreatedAt": 1644096553000,
    "Text": "A Revolução começou 2",
    "InReplyToStatusId": 1,
    "InReplyToUserId": 1,
    "InReplyToScreenName": "",
    "Place": false,
    "Retweeted": true,
    "FavoriteCount": 1,
    "Retweet": false,
    "RetweetCount": 1,
    "RetweetedByMe": false,
    "CurrentUserRetweetId": "",
    "PossibleSensitive": false,
    "Lang": "PTP",
    "User": {
        "Name": "Alberto Roberto",
        "OriginalProfileImageURL": "",
        "ProfileImageURLHttps": "",
        "BiggerProfileImageURLHttps": "https://pbs.twimg.com/profile_images/1462058322232844295/DTv7M8lC_normal.jpg",
        "MiniProfileImageURLHttps": "",
        "OriginalProfileImageURLHttps": "",
        "DefaultProfileImage": true,
        "URL": "",
        "Protected": false,
        "FollowersCount": 100,
        "ProfileBackgroundColor": "",
        "ProfileTextColor": "",
        "ProfileLinkColor": "",
        "ProfileSidebarFillCollor": "",
        "ProfileSidebarBorderColor": "",
        "ProfileUserBackgroundImage": false,
        "DefaultProfile": true,
        "ShowAllInlineMedia": true,
        "FriendsCount": 2000,
        "CreatedAt": 1644096553000,
        "FavouritesCount": 21321321,
        "Lang": "PT",
        "StatusesCount": 1,
        "GeoEnabled": false,
        "Verified": false,
        "Translator": false,
        "ListedCount": 1,
        "FollowRequestSent": false,
        "ScreenName": "Netflix",
        "Location": "",
        "Description": "",
        "ContributorsEnabled": false,
        "ProfileImageURL": "",
        "BiggerProfileImageURL": "",
        "MiniProfileImageURL": ""
    }
}



### 
GET http://localhost:3000/mail-list


###
POST http://localhost:3000/mail-list
Content-Type: application/json

{
    "emails": [
        "user@teste.com",
        "user2@teste.com",
        "user3@teste.com"
    ]
}
