GET http://localhost:3000/tweets



### 
POST http://localhost:3000/tweets
Content-Type: application/json

{
    "Text": "A Imersão começou",
    "User": {
        "Name": "Luiz Carlos"
    }
}

### 
POST http://localhost:3000/tweets
Content-Type: application/json

{
    "Text": "Um novo tweet chegou 10",
    "User": {
        "Name": "Luiz Carlos"
    }
}



### 
GET http://localhost:3000/mail-list


###
POST http://localhost:3000/mail-list
Content-Type: application/json

{
    "emails": [
        "user@teste.com",
        "user2@teste.com",
        "user3@teste.com"
    ]
}
